//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public int MaterialID { get; set; }
        public int ColorID { get; set; }
        public decimal Price { get; set; }
        public int CountryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual CountryID CountryID1 { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
